#!/usr/bin/env bun
/**
 * Verification test for keyminer GPU output.
 * Takes results from a keyminer run, verifies each private key produces the
 * correct address, signs a message, and recovers the public key to confirm
 * the full cryptographic pipeline matches.
 *
 * ⚠️  WARNING: All private keys and addresses in this file are TEST-ONLY.
 *    They were generated by GPU mining for testing purposes and are now PUBLIC.
 *    DO NOT send real funds to any of these addresses — they are compromised.
 */

import { Wallet, verifyMessage, SigningKey, computeAddress } from "ethers";

// ── Test data from GPU mining runs ───────────────────────────────────
// These key-address pairs were discovered by the GPU miner and verified
// against ethers.js. They are PUBLIC TEST DATA — never use for real funds.
const TEST_VECTORS = [
  {
    privateKey: "0x0000000000000000000000000000000000000000000000000000000000000001",
    expectedAddress: "0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf",
  },
  {
    privateKey: "0x0000000000000000000000000000000000000000000000000000000000000002",
    expectedAddress: "0x2B5AD5c4795c026514f8317c7a215E218DcCD6cF",
  },
  {
    privateKey: "0x0000000000000000000000000000000000000000000000000000000000d84097",
    expectedAddress: "0x90725485F127f89bf8DF8d77260fff3E802f6749",
  },
  {
    privateKey: "0x0000000000000000000000000000000000000000000000000000000000240d9f",
    expectedAddress: "0x1dfC9e6720242eB51273Efe7A8243C386176cc78",
  },
  {
    privateKey: "0x0000000000000000000000000000000000000000000000000000000000200577",
    expectedAddress: "0x4B80aE40328DbEA9e6c0E749C0e905fcBf1FEaDa",
  },
  {
    privateKey: "0x0000000000000000000000000000000000000000000000000000000000dcee73",
    expectedAddress: "0x6cAF30eF66f820D0E332659BF732600BDD1344D7",
  },
];

const TEST_MESSAGE = "keyminer verification test";

console.log("╔══════════════════════════════════════════════════════════════╗");
console.log("║  KEYMINER VERIFICATION TEST                                ║");
console.log("║                                                            ║");
console.log("║  ⚠️  All keys below are PUBLIC TEST DATA — never use for   ║");
console.log("║     real funds. They are considered public and not safe for any real use. ║");
console.log("╚══════════════════════════════════════════════════════════════╝");
console.log();

let passed = 0;
let failed = 0;

for (const vec of TEST_VECTORS) {
  const label = `key=${vec.privateKey.slice(0, 10)}...${vec.privateKey.slice(-6)}`;
  try {
    // 1. Derive address from private key
    const wallet = new Wallet(vec.privateKey);
    const derivedAddress = wallet.address;

    // 2. Verify address matches expected
    if (derivedAddress.toLowerCase() !== vec.expectedAddress.toLowerCase()) {
      console.log(`  FAIL ${label}: address mismatch`);
      console.log(`    expected: ${vec.expectedAddress}`);
      console.log(`    got:      ${derivedAddress}`);
      failed++;
      continue;
    }

    // 3. Sign a message
    const signature = await wallet.signMessage(TEST_MESSAGE);

    // 4. Recover signer address from signature
    const recoveredAddress = verifyMessage(TEST_MESSAGE, signature);
    if (recoveredAddress.toLowerCase() !== derivedAddress.toLowerCase()) {
      console.log(`  FAIL ${label}: signature recovery mismatch`);
      console.log(`    signed by:  ${derivedAddress}`);
      console.log(`    recovered:  ${recoveredAddress}`);
      failed++;
      continue;
    }

    // 5. Verify public key derivation matches
    const signingKey = new SigningKey(vec.privateKey);
    const pubKeyUncompressed = signingKey.publicKey; // 0x04 + x + y
    const addrFromPubKey = computeAddress(pubKeyUncompressed);
    if (addrFromPubKey.toLowerCase() !== derivedAddress.toLowerCase()) {
      console.log(`  FAIL ${label}: pubkey→address mismatch`);
      failed++;
      continue;
    }

    console.log(`  PASS ${label}`);
    console.log(`    addr: ${derivedAddress}`);
    console.log(`    sig:  ${signature.slice(0, 20)}...`);
    console.log(`    pubkey→addr verified`);
    passed++;
  } catch (e) {
    console.log(`  FAIL ${label}: ${e}`);
    failed++;
  }
}

console.log();
console.log(`Results: ${passed} passed, ${failed} failed out of ${TEST_VECTORS.length} tests`);
console.log();
console.log("⚠️  REMINDER: All private keys above are PUBLIC TEST DATA.");
console.log("   They are considered public and not safe for any real use.");

if (failed > 0) {
  process.exit(1);
}
